"""add session token

Revision ID: b071bd0defb2
Revises: 41e56bd272f5
Create Date: 2026-10-09 11:49:17.085660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b071bd0defb2'
down_revision: Union[str, Sequence[str], None] = '41e56bd272f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authentication_sessions', sa.Column('session_token', sa.String(length=128), nullable=False))
    op.create_index(op.f('ix_authentication_sessions_session_token'), 'authentication_sessions', ['session_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authentication_sessions_session_token'), table_name='authentication_sessions')
    op.drop_column('authentication_sessions', 'session_token')
    # ### end Alembic commands ###
